version: '3'
services:
  redis:
    container_name: cache
    image: 'redis'
    expose: 
      - 6379
  node-app:
    container_name: app
    restart: on-failure
    build: .
    ports:
      - "5000:5000"
    environment:
      - REDIS_URL=redis://cache
