version: "3"
services:
  node1:
    container_name: node1
    build: .
    ports: 
      - "5000:5000"
  node2:
    container_name: node2
    build: 
      context: .
      dockerfile: Dockerfile2
    ports: 
      - "5000:5000"

